// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiamondShopSystem.Data.Models;

public partial class RequestDetail
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Jewelry { get; set; }

    public string Price { get; set; }

    public string ReqId { get; set; }

    public virtual Request Req { get; set; }
}